name: Testing daph_api

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: snok/install-poetry@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Install project
      run: poetry install --no-interaction
    - name: Run black check
      run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: snok/install-poetry@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Install project
      run: poetry install --no-interaction
    - name: Run flake8 check
      run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: snok/install-poetry@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Install project
      run: poetry install --no-interaction
    - name: Run mypy check
      run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: snok/install-poetry@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Install project
      run: poetry install --no-interaction
    - name: Run pytest check
      run: poetry run pytest -vv --cov="daph_api" .
      env:
        DAPH_API_HOST: "0.0.0.0"
